### ISSUE TITLE
Consider intuitive syntax for result stubbing, for use in unit-tests in other systems on how those systems handle faults

### ISSUE THREAD

**Issue by reisenberger** [Polly-Contrib/Simmy#16]
Alongside **chaos-engineering**, another significant use-case for Simmy is **setting up calls to return stub/fake results, for unit tests**.

We already have the functionality, [`InjectResultImplementation`](https://github.com/App-vNext/Simmy/blob/v0_1/src/Simmy/MonkeyEngine.cs#L67-L81), but all our syntax uses the wording [`InjectFault`](https://github.com/App-vNext/Simmy/blob/v0_1/src/Simmy/Fault/InjectFaultSyntax.cs).  

Not all results one might want to inject, in unit testing, are faults. Success cases are valid to test.  A more neutral syntax to support this would be `InjectResult`, eg:

    MonkeyPolicy.InjectResult<HttpResponseMessage>(new HttpResponseMessage(HttpStatusCode.OK))

### Proposal I

+ Rename the `Fault` namespaces to be `Outcomes` (ie `Simmy.Outcomes`), in both `Simmy` and `Simmy.Specs`,
+ Add files `InjectResultSyntax` and `AsyncInjectResultSyntax`, giving various overloads `InjectResult<TResult>(...)` and `InjectResultAsync<TResult>(...)` 
+ These overloads would be _identical_ to the existing `InjectFault<TResult>(...)` overloads.  To avoid code duplication, likely the `InjectResult(...)` overloads should be the master code, and `InjectFault(...)` overloads should simply chain to the corresponding `InjectResult(...)` overload.

_Advantages/disadvantages_: Retains existing `InjectFault<TResult>(...)` syntax, but leaves some minor duplication, as there would be two syntaxes (`InjectFault<TResult>(...)` and `InjectResult<TResult>(...)`) which cause identical behaviour.  But gives nice-reading syntax for each use case.

### Proposal II

+ Rename the `Fault` namespaces to be `Outcomes` (ie `Simmy.Outcomes`), in both `Simmy` and `Simmy.Specs`,
+ Rename the existing `InjectFault<TResult>(...)` overloads to be `InjectResult(...)`.
+ Rename the existing `InjectFault(Exception ...)` overloads to be `InjectException(...)`.

_Advantages/disadvantages_: No duplication. Loss of `InjectFault(...)` syntax.

### Timing

_Would be nice to have this before launch, as stubbing for unit-tests is a major use case we can advertise, as part of the launch_

**Comment by reisenberger** [comment]
Maybe we take this out of scope of the initial launch, so that we can get a first chaos-engineering version out.

Leaving the issue open, but removing the 'Initial launch' milestone

**Comment by mebjas** [comment]
Is this a major use case?

**Comment by vany0114** [comment]
I think it will be. Actually a few weeks ago, a bunch of co-workers were asking and looking for a tool to mock a HttpStatusCode (Ok, 401, etc) --I'm not saying that due to my co-workers were asking about that that's gonna be a major use case, but I think that's a pretty common needed when it comes to unit test and mocking those kinds of scenarios, and it will great if our API offers it, mostly because there are a lot of people out there that love Polly and we can take advantage of that and make popular those features inside Simmy--

Regarding the proposals, I like the most the second one, but I think it's too soon to make breaking changes on releases since we're gonna end up loose the `InjectFault` syntax. 

I might take care of this if you guys want.
