### ISSUE TITLE
Unable to wrap fault policies?

### ISSUE THREAD

**Issue by benpeart** [Polly-Contrib/Simmy#53]
I'm new to C#, Polly and Simmy but after reading all the docs and looking at the samples, I thought I'd try to update the Polly sample to use Simmy to generate failures instead of the custom throttling handler.  

I copy/pasted the fault injection samples from https://github.com/Polly-Contrib/Simmy/blob/master/README.md ("Step 1") into ValuesController.cs.  I then tried to wrap them together using PolicyWrap() before calling Execute but am getting a compiler error:

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1503	Argument 1: cannot convert from 'Polly.Contrib.Simmy.Fault.InjectOutcomePolicy<System.Net.Sockets.SocketException>' to 'Polly.ISyncPolicy'	PollyTestApp	C:\src\Polly-Samples\PollyTestApp\Controllers\ValuesController.cs	39	Active

What am I missing?  Why can't the fault policy be wrapped like the other policy types?

I forked the Polly-Sample repo and created a PR with my attempted changes which should make figuring out what I'm attempting easier to see:

https://github.com/App-vNext/Polly-Samples/pull/22/files

**Comment by vany0114** [comment]
Hi @benpeart 

That error is because you're trying to execute two different kinds of policies: `IPolicy<>` and `IPolicy`, since your [fault policy](https://github.com/App-vNext/Polly-Samples/blob/a840e5de2ace1d0b49188ab3c039e3527f6da067/PollyTestApp/Controllers/ValuesController.cs#L25) is returning an `IPolicy<SocketException>` and your [latency policy](https://github.com/App-vNext/Polly-Samples/blob/a840e5de2ace1d0b49188ab3c039e3527f6da067/PollyTestApp/Controllers/ValuesController.cs#L32) is returning an `IPolicy`, so in order to wrap them, both of them should be either `IPolicy` or `IPolicy<>`, but you can't mix them in one single execution.

So, in the example you provided you could do something like this:

```
public IEnumerable<string> Get()
{
    // Following example causes the policy to throw SocketException with a probability of 50% if enabled
    var fault = new SocketException(errorCode: 10013);
    var chaosFault = MonkeyPolicy.InjectFault<IEnumerable<string>>(
                fault,
                injectionRate: 0.5,
                enabled: () => { return true; }
            );

    // Following example causes policy to introduce an added latency of 5 seconds to a randomly-selected 10% of the calls.
    var chaosLatency = MonkeyPolicy.InjectLatency<IEnumerable<string>>(
                latency: TimeSpan.FromSeconds(5),
                injectionRate: 0.1,
                enabled: () => { return true; }
            );

    // Wrap the chaos policies using PolicyWrap
    var chaosPolicy= Policy.Wrap(chaosFault, chaosLatency);

    return chaosPolicy.Execute(() => new string[] { "value1", "value2" });
}
```

Notice, that both policies return `IEnumerable<string>` which is the return type of the method that is being executed.

**Comment by vany0114** [comment]
However, I noticed that we have a kind of collision among the overloads with the form of: 

```
InjectFault(Exception, Double, Func<Context, CancellationToken, bool>)
```
and 
```
InjectFault<TResult>(TResult, Double, Func<Context, CancellationToken, bool>)
```

Because it's taking the second one by default given the compiler priorities, so, a workaround in your original code might be:
```
var chaosFault = MonkeyPolicy.InjectFault(
    (Exception)fault,
    injectionRate: 0.5,
    enabled: () => { return true; }
);
```

Fortunately, we're working on a [new syntax](https://github.com/Polly-Contrib/Simmy/pull/49) which is gonna be released soon, because we realized how complex might be having/maintaining all those overloads. (not to mention the confusion that it generates to the devs) Said that this problem will go away, so you'll be able to do something like this:

```
public IEnumerable<string> Get()
{
    // retuns IPolicy instead of IPolicy<SocketException>
    var fault = new SocketException(errorCode: 10013);
    var chaosFault = MonkeyPolicy.InjectFault(with =>
                with.Fault(fault)
                    .Enabled()
                    .InjectionRate(0.5)
    );

    var chaosLatency = MonkeyPolicy.InjectLatency(with =>
                with.Latency(TimeSpan.FromSeconds(5))
                    .InjectionRate(0.1)
                    .Enabled()
    );

    // Wrap the chaos policies using PolicyWrap
    var chaosPolicy= Policy.Wrap(chaosFault, chaosLatency);
    return chaosPolicy.Execute(() => new string[] { "value1", "value2" });
}
```

So @benpeart , thanks for letting us know about it because we weren't aware of this behavior!

---
**Note:** the old syntax (the current one as the time I'm writing this) is gonna be deprecated.

**Comment by benpeart** [comment]
Thank you!  That was very helpful.  The workaround works great and I'm looking forward to the new/updated/enhanced syntax!

**Comment by stewartadam** [comment]
Has this been resolved resolved for `InjectResult<>`? It still does not appear to be possible to wrap `InjectResult<>` and `InjectException` policies for example:
```c#
var chaosFault = MonkeyPolicy.InjectExceptionAsync(with =>
                with.Fault(new SocketException(errorCode: 10013))
                    .Enabled()
                    .InjectionRate(0.5));

            // TODO: wrap with multiple faults - not possible due to type-safety
            // https://github.com/Polly-Contrib/Simmy/issues/53
            var internalFault = MonkeyPolicy.InjectResultAsync<HttpResponseMessage>(with =>
                with.Result(new HttpResponseMessage(HttpStatusCode.InternalServerError))
                    .InjectionRate(1)
                    .Enabled());

            var combinedPolicy1 = Policy.WrapAsync(chaosFault, internalFault);
            var combinedPolicy2 = Policy.WrapAsync<HttpResponseMessage>(chaosFault, internalFault);
```

combinedPolicy1 errors with
```
Argument 2: cannot convert from 'Polly.Contrib.Simmy.Outcomes.AsyncInjectOutcomePolicy<System.Net.Http.HttpResponseMessage>' to 'Polly.IAsyncPolicy'
```

combinedPolicy2 errors with
```
Argument 1: cannot convert from 'Polly.Contrib.Simmy.Outcomes.AsyncInjectOutcomePolicy' to 'Polly.IAsyncPolicy<System.Net.Http.HttpResponseMessage>'
```
